---
  - name: Check the remote host uptime
    hosts: all
    tasks:
      - name: Execute the Uptime command over Command module
        register: uptimeoutput
        command: "uptime"

      - debug:
          var: uptimeoutput.stdout_lines
          
 - name:  Copying jar to remote EC2 container
   hosts:  all
   tasks:
     - name: Copying jar with playbook
       become: true
       copy:
       src: 
