---
  - hosts: all
    become: true
    tasks:
    - name: Check the remote host uptime
      register: uptimeoutput
      command: "uptime"

    - debug:
        var: uptimeoutput.stdout_lines
          
    - name: Copying jar to remote EC2 container
      copy:
        src: ../dwptest/target/dwptest-0.0.1-SNAPSHOT.jar
        dest: /home/ec2-user
        owner: ec2-user
        group: ec2-user
        mode: 0644
          
    - name: Update all packages
      yum: 
        name: '*'
        state: latest
        update_only: yes
          

          
  
